### PR TITLE
fix(postcss-merge-longhand): Should not mangle borders (#579)

### LINKED ISSUE #579: Invalid CSS output when combining border:none and border-color
**Input:**
```css
.test {
  border-bottom: none;
  border-color: red;
}
```
**Output:**
```css
.test{border-bottom:none none red;border-left-color:red;border-right-color:red;border-top-color:red}
```
**Expected:**
```css
.test{border-bottom: none;border-color: red}
```

Note: `border-bottom: none none red` is invalid.

And if you replace `border-bottom: none` with `border: none` the output is also invalid:
```css
.test{border:none none red}
```

cssnano version: 4.0.5

### PR DESCRIPTION
**Pull request by andyjansson**
Fixes #579. 

The changes should also lead to slightly better compression (e.g. [1](https://github.com/cssnano/cssnano/pull/583/files#diff-b6189c20f0edb0a28d43eb41e7e241f1L3199)).

### CODE REVIEW

File: packages/postcss-merge-longhand/src/__tests__/borders.js [hunk 1]
```diff
@@ -154,6 +154,20 @@ test(
     'hr{display:block;height:1px;border:0;border-top:1px solid #ddd}'
 );
 
+test(
+    'Should not mangle borders (#579) (1)',
+    processCSS,
+    'h1{border-bottom:none;border-color:red}',
+    'h1{border-bottom:0;border-color:red}',
```
Comment (evilebottnawi) [inline packages/postcss-merge-longhand/src/__tests__/borders.js]: `border: none` !== `border: 0` https://stackoverflow.com/questions/2922909/should-i-use-border-none-or-border-0

Comment (evilebottnawi) [reply packages/postcss-merge-longhand/src/__tests__/borders.js]: It is no safe

File: packages/postcss-merge-longhand/src/__tests__/borders.js [hunk 2]
```diff
@@ -431,9 +461,9 @@ test(
 );
 
 test(
-    'Should not convert currentColor (#559)',
+    'Should not convert currentcolor (#559)',
```
Comment (evilebottnawi) [inline packages/postcss-merge-longhand/src/__tests__/borders.js]: Can we also add test with `currentColor` (some people use this writing style in code)?
