### PR TITLE
fix(postcss-reduce-idents): fix line names grid templates

### LINKED ISSUE #529: [Bug] named grid-template-columns are not renamed while grid-area does
version: 3.10.0
preset: default

input: 
```scss
.test{
  grid-template-columns: [image] 100px [info] auto;
}

.test a{
  grid-area: image;
}
```

cssnano output:
```scss
.test {
  grid-template-columns: [image] 100px [info] auto
}

.test a {
  grid-area: a
}
```

### PR DESCRIPTION
**Pull request by ludofischer**
Handle grid and column names enclosed in square brackets. Cover both the case where the brackets contain a single grid line name and the case where the brackets contain multiple separate grid line names.

Fix #529 (again)

### CODE REVIEW

File: packages/postcss-reduce-idents/src/lib/grid-template.js [hunk 1]
```diff
@@ -53,6 +55,19 @@ module.exports = function () {
               }
             });
           }
+          if (child.type === 'word') {
+            const word = child.value;
+            if (word.startsWith('[') && word.endsWith(']')) {
```
Comment (ludofischer) [inline packages/postcss-reduce-idents/src/lib/grid-template.js:60]: Maybe there's a better way to do it, but postcss-value-parser does not understand list of elements in brackets at all.

**Comment by ludofischer** [comment]
@alexander-akait do you think we can merge this?

**Review by alexander-akait — APPROVED** [review]
