### PR TITLE
fix(postcss-discard-empty): preserve empty custom properties

### LINKED ISSUE #1350: [Bug]: discardEmpty removes empty custom property
### Describe the bug

In TailwindCSS, many custom properties are set, like `--tw-grayscale:  ;` A class like `.blur` sets following CSS:
```css
.blur {
  --tw-blur: blur(8px);
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}
```

The problem is, if the class `.grayscale` is not used (who set a value, just like blur) the custom property get's removed and the class `blur` doesn't work anymore.

### Expected behaviour

The custom properties should not be removed, when a class relies on the empty property

### Steps to reproduce

I uploaded an example here: https://github.com/jonnitto/cssNanoDiscardEmpty: In the folder `disabled` the setting is disabled, in the folder `enabled`, the setting is enabled

I formatted `main.css`, so you can spot fast the difference.

### Version

5.1.1

### Preset

default

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 399.27 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
```

### Package details

```shell
├─┬ autoprefixer@10.4.2
│ └── postcss@8.4.8 deduped
├─┬ cssnano@5.1.1
│ ├─┬ cssnano-preset-default@5.2.1
│ │ ├─┬ css-declaration-sorter@6.1.4
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ cssnano-utils@3.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-calc@8.2.4
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-colormin@5.3.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-convert-values@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-discard-comments@5.1.1
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-discard-duplicates@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-discard-empty@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-discard-overridden@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-merge-longhand@5.1.0
│ │ │ ├── postcss@8.4.8 deduped
│ │ │ └─┬ stylehacks@5.1.0
│ │ │   └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-merge-rules@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-minify-font-values@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-minify-gradients@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-minify-params@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-minify-selectors@5.2.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-charset@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-display-values@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-positions@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-repeat-style@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-string@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-timing-functions@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-unicode@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-url@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-normalize-whitespace@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-ordered-values@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-reduce-initial@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-reduce-transforms@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-svgo@5.1.0
│ │ │ └── postcss@8.4.8 deduped
│ │ ├─┬ postcss-unique-selectors@5.1.1
│ │ │ └── postcss@8.4.8 deduped
│ │ └── postcss@8.4.8 deduped
│ └── postcss@8.4.8 deduped
├─┬ postcss-cli@9.1.0
│ ├─┬ postcss-reporter@7.0.5
│ │ └── postcss@8.4.8 deduped
│ └── postcss@8.4.8 deduped
├── postcss@8.4.8
└─┬ tailwindcss@3.0.23
  ├─┬ postcss-js@4.0.0
  │ └── postcss@8.4.8 deduped
  ├─┬ postcss-nested@5.0.6
  │ └── postcss@8.4.8 deduped
  └── postcss@8.4.8 deduped
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ludofischer**
Fix #1350

Empty custom properties are valid according to the latest spec updates and various CSS tricks use them.

### CODE REVIEW

File: packages/postcss-discard-empty/test/index.js [hunk 1]
```diff
@@ -85,6 +85,11 @@ test(
   passthroughCSS('h1{/*comment*/}')
 );
 
+test(
+  'should preserve empty custom properties',
+  passthroughCSS('*{--tw-shadow:;}')
```
Comment (alexander-akait) [inline packages/postcss-discard-empty/test/index.js:90]: It should be ` ` (empty space), chrome has bug with it, anyway empty value is valid too

**Review by alexander-akait — COMMENTED** [review]
Looks good, some tools handle it and always inject white space when it doesn't have empty space (like a fix)

File: packages/postcss-discard-empty/test/index.js (hunk 1 above)
Comment (ludofischer) [reply packages/postcss-discard-empty/test/index.js]: postcss-discard-empty already did not remove the property if the value is a space, the bug occurred in combination with postcss-normalize-whitespace (first postcss-normalize-whitespace would trim the space, reducing the value to empty, which would cause discard-empty to remove it).

Comment (ludofischer) [reply packages/postcss-discard-empty/test/index.js]: I've added a property with a space value to the test just as a reminder, although that case already passed before.

**Comment by ludofischer** [comment]
> Looks good, some tools handle it and always inject white space when it doesn't have empty space (like a fix)

We could do that in `postcss-normalize-whitespace`.

**Comment by ludofischer** [comment]
I've rebased this on top of https://github.com/cssnano/cssnano/pull/1352 to see how all the changes work together. Seems fine.

**Review by alexander-akait — APPROVED** [review]
Honestly, spec says that we should not touch custom components, because they can be used in any context and space can have any meaning, but it is exotic usage

**Comment by ludofischer** [comment]
> Honestly, spec says that we should not touch custom components, because they can be used in any context and space can have any meaning, but it is exotic usage

I thought that the amount of whitespace did not matter (so 1 space can replace any amount), but it's true I cannot find anything conclusive. [CSS Syntax Module Level 3](https://drafts.csswg.org/css-syntax/#consume-a-declaration) seems to imply that any value made of only whitespaces would reduce to an empty value:

> While the last token in the declaration’s value is a [whitespace-token](https://drafts.csswg.org/css-syntax/#typedef-whitespace-token), [remove](https://infra.spec.whatwg.org/#list-remove) that token

If the value is all whitespaces, the last token is goingg to be a whitespace until there are no more tokens left.
