### PR TITLE
fix ben-eb/cssnano/448 don't remove fallbacks for custom css properties

### LINKED ISSUE #448: mergeLonghand is not always a safe transformation
The [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) plugin sets fallbacks for properties that use native CSS custom properties. Unfortunately, I noticed cssnano was stripping these fallbacks out, and I traced it back to the mergeLonghand plugin.

Here's an example of what `postcss-custom-properties` does that gets stripped by mergeLonghand:

```css
:root {
  --gutter: 1em;
}

.component {
  padding: var(--gutter);
}

/* becomes */

:root {
  --gutter: 1em;
}

.component {
  padding: 1em;  
  padding: var(--gutter);
}
```

But since cssnano sees two `padding` declarations, it tries to combine them to a single, longhand version. However, when doing that the fallback is lost.

### PR DESCRIPTION
**Pull request by karapetyan**
@ai could you check, please. 
Thanks.

fixes #448

### CODE REVIEW

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js [hunk 1]
```diff
@@ -154,3 +154,38 @@ test(
...
+    processCss,
+    'h1{padding-top:var(--variable);padding-right:var(--variable);padding-bottom:var(--variable);padding-left:var(--variable)}',
+    'h1{padding:var(--variable)}'
+);
+
+test(
+    'should not break unmergeable fallbacks with custom props (2)',
+    processCss,
+    'h1{padding:10em;padding:var(--variable)}',
+    'h1{padding:var(--variable);padding:10em}'
```
Comment (andyjansson) [inline packages/cssnano/src/__tests__/postcss-merge-longhand.js]: This looks wrong. Surely the output should be the same as the input..?

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js [hunk 2]
```diff
@@ -154,3 +154,38 @@ test(
     'h1{margin:10px 20px 30px 40px}',
     'h1{margin:10px 20px 30px 40px}',
 );
+
+test(   
+    'should merge custom props and dont remove fallbacks',
+    processCss,
+    'h1{padding-top:10px;padding-right:15px;padding-bottom:20px;padding-left:25px;padding-top:var(--variable);padding-right:var(--variable);padding-bottom:var(--variable);padding-left:var(--variable)}',
+    'h1{padding:var(--variable);padding:10px 15px 20px 25px}'
```
Comment (andyjansson) [inline packages/cssnano/src/__tests__/postcss-merge-longhand.js]: Shouldn't it be: 
```
 h1{padding:10px 15px 20px 25px;padding:var(--variable)}
```
?

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js (hunk 1 above)
Comment (karapetyan) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: As described in issue https://github.com/ben-eb/cssnano/issues/448
cssnano shouldn't remove fallbacks for custom CSS properties.

As far i understand that exactly what fix should do.

Comment (andyjansson) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: Yes, but the correct order should be: 

```
h1{padding:10em;padding:var(--variable)}
```

`var(--variable)` wouldn't be understood by browsers not supporting it, thus falling back on `10em`. In your case, you overwrite `var(--variable) ` with `10em` in all cases.

Comment (evilebottnawi) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: @karapetyan yep, we should have `h1{padding:10em;padding:var(--variable)}` here

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js (hunk 2 above)
Comment (karapetyan) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: If we look at many other tests that contain more than one unmegable rule, they have similar behavior. 

Here is some examples from same test file:
```javascript
test(
    'should not merge padding values with mixed !important',
    processCss,
    'h1{padding-top:10px!important;padding-right:20px;padding-bottom:30px!important;padding-left:40px}',
    'h1{padding-bottom:30px!important;padding-left:40px;padding-right:20px;padding-top:10px!important}',
);

test(
    'should not merge identical border values with mixed !important',
    processCss,
    'h1{border-top:1px solid #000;border-bottom:1px solid #000;border-left:1px solid #000!important;border-right:1px solid #000!important}',
    'h1{border-bottom:1px solid #000;border-left:1px solid #000!important;border-right:1px solid #000!important;border-top:1px solid #000}',
);
```
so I guess this is correct behavior

Comment (andyjansson) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: I disagree, the semantics have fundamentally changed. See my other comment.

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js (hunk 1 above)
Comment (karapetyan) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: @andyjansson @evilebottnawi understood, thanks for review :) I’ll fix it soon.

File: packages/postcss-merge-longhand/src/lib/getLastNode.js [hunk 3]
```diff
@@ -1,3 +1,30 @@
...
+        ).filter(Boolean)
+    );
+}
+
+export function getRulesWithAndWithoutCustomProps (props, properties) {
+    return new Array(
+        getRulesWithoutCustomProps(props, properties),
+        getRulesWithCustomProps(props, properties)
+    );
+}
```
Comment (evilebottnawi) [inline packages/postcss-merge-longhand/src/lib/getLastNode.js]: Looks we should rename this file to `utils.js`

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js (hunk 2 above)
Comment (karapetyan) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: @andyjansson done, thanks for help!

File: packages/cssnano/src/__tests__/postcss-merge-longhand.js (hunk 1 above)
Comment (karapetyan) [reply packages/cssnano/src/__tests__/postcss-merge-longhand.js]: @evilebottnawi friendly ping

**Comment by andyjansson** [comment]
Can you add a test where the properties are mixed up to demonstrate its correctness? E.g.:

```
h1{
  padding-top:10px;
  padding-right:var(--variable);
  padding-right:15px;
  padding-bottom:var(--variable);
  padding-bottom:20px;
  padding-left:25px;
  padding-top:var(--variable);
  padding-left:var(--variable)
}
```

**Comment by karapetyan** [comment]
@andyjansson done

**Comment by andyjansson** [comment]
@karapetyan okay, looking at the final test, I don't think the implementation is correct. `padding-right` and `padding-bottom` should be overwritten by concrete values, while the rest should not.

**Comment by evilebottnawi** [comment]
@andyjansson can you explain what tests we should add more?

**Comment by andyjansson** [comment]
The correct minification should be something like: 

```
h1{
  padding: 10px 15px 20px 25px;
  padding-left:var(--variable)
  padding-top:var(--variable);
}
```

**Comment by karapetyan** [comment]
@andyjansson previous implementation was overcoded and awful, thank you for review. What you think about new one?

**Comment by andyjansson** [comment]
I'll be off this weekend, so I won't be able to properly review this until Monday. But at first glance, it seems good.

**Comment by evilebottnawi** [comment]
@andyjansson :+1: i will close other problems for `cssnano@4` and Monday after review we can merge this and maybe release `rc.3`, when two-three week and release stable 4 version

**Comment by andyjansson** [comment]
Alright, the implementation looks good. I was a bit confused by the odd ordering of the properties in the tests until I realised I was looking at integration tests (the reordering is due to css-declaration-sorter). 

I'd like some unit tests where we test the plugin in isolation as well, if you don't mind (under `/packages/postcss-merge-longhand/src/__tests__`). The other thing that caught my eye was `isCustomProp` which could possibly be written so that false-positives are less likely to happen. 

Apart from that, it looks really good. Good job!

**Comment by karapetyan** [comment]
@andyjansson @evilebottnawi great review, thank you guys. It was review driven development, actually)

File: packages/postcss-merge-longhand/src/lib/isCustomProp.js [hunk 4]
```diff
@@ -0,0 +1,2 @@
+export default node => 
+    ~node.value.search(/var(\s+\(|\()(\s+--|--)/i);
```
Comment (andyjansson) [inline packages/postcss-merge-longhand/src/lib/isCustomProp.js]: this could be simplified a bit. E.g.:

```js
~node.value.search(/var\s*\(\s*--/i);
```
Last nitpick, I promise!

**Comment by evilebottnawi** [comment]
@karapetyan Thanks!

**Comment by YozhikM** [comment]
```bash
/home/stanislav/projects/cssnano/packages/postcss-merge-longhand/src/__tests__/borders.js
  316:5  error  'processCss' is not defined  no-undef
  323:5  error  'processCss' is not defined  no-undef
  330:5  error  'processCss' is not defined  no-undef
```

**Comment by YozhikM** [comment]
@karapetyan @evilebottnawi 
I actually came for someone else, I think it's necessary to fix it, but not in my PR

**Comment by evilebottnawi** [comment]
@YozhikM PR welcome :+1:
