### PR TITLE
fix: do not mangle `@page :first` rules (closes #677)

### LINKED ISSUE #677: Incorrect handling of `@page :first`
Hi,

While trying to debug an issue in another package (https://github.com/symfony/webpack-encore/issues/498), it seems the root cause might come from an incorrect output produced by `cssnano`.

The [:first](https://developer.mozilla.org/fr/docs/Web/CSS/:first) pseudo-class can be used with `@page` to specify a set of rules that will only be applied to the first page of a printed document (using `@media print {}`).

The correct syntax of the selector is `@page :first` (according to the doc on MDN https://developer.mozilla.org/fr/docs/Web/CSS/:first) and `cssnano` seems to handle it erroneously.

The **`:`** before `first` is turned into a **`,`** as seen here : 

demo from the playground

I'm not sure how/where to look in the code to try and fix this, please let me know if there is anything more I can do to help or if I'm mistaken and this is an error on my part.

### PR DESCRIPTION
**Pull request by MrMitch**
The `:first` pseudo-class is meant to be used with the `@page` at-rule to apply some style to the first page of a printed document (https://developer.mozilla.org/en-US/docs/Web/CSS/:first).

The `minifyParams` optimization causes it to be mangled :
it's transformed from
`@page :first { margin: 0 }`
to
`@page ,first { margin: 0 }`.

This commit fixes this behavior and closes cssnano/cssnano#677

### CODE REVIEW

File: packages/postcss-minify-params/src/index.js [hunk 1]
```diff
@@ -34,7 +34,14 @@ function transform (legacy, rule) {
...
     // @value vertical, center from "./foo.css";
-    if (!rule.params || rule.name.toLowerCase() === 'value') {
+    //
+    // We should also not re-arrange pseudo-classes for @page at-rule.
+    // For example:
+    //
+    // @page :first { margin: 0; }
+    const ruleName = rule.name.toLocaleLowerCase();
+    if (!rule.params ||
+        rule.type === 'atrule' && (ruleName === 'value' || ruleName === 'page')) {
```
Comment (evilebottnawi) [inline packages/postcss-minify-params/src/index.js]: Good job! no need `rule.type === 'atrule'`, because we already in `walkAtRules` and all rules here are `atrule`

Comment (MrMitch) [reply packages/postcss-minify-params/src/index.js]: @evilebottnawi Thank you for pointing this out, I fixed it and pushed the changes.

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by MrMitch** [comment]
@evilebottnawi thank you for merging this. Do you know if a release containing the 2 PR that were merged since the last release could be possible ?

**Comment by evilebottnawi** [comment]
@MrMitch yep, today i will do release (some busy right now)

**Comment by MrMitch** [comment]
@evilebottnawi thank you very much !

**Comment by evilebottnawi** [comment]
@MrMitch sorry for delay, i have some ideas how we can improve speed of `cssnano` and some of them already implemented (increase perf around 2x-3x), tomorrow i have been ending code review for more perf improvement and do release, thanks

**Comment by MrMitch** [comment]
Thank you, these will be great additions to the release. Take your time, thank you for doing this!

**Comment by MrMitch** [comment]
hi @evilebottnawi, did you manage to commit all the performance improvements that you wanted to do before the release ?

**Comment by evilebottnawi** [comment]
@MrMitch almost everything, today will be release

**Comment by MrMitch** [comment]
@evilebottnawi awesome, thank you !
